<a href="https://colab.research.google.com/github/danish123-a/cancer-classification-with-using-ANN/blob/main/mini_batch_gradien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
v=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")


In [9]:
v

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [11]:
v=v.drop(columns=["id","Unnamed: 32"])

In [12]:
v

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [15]:
x_train,x_test,y_train,y_test=train_test_split(v.iloc[:,1:],v.iloc[:,0],test_size=0.2)

In [16]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
396        13.51         18.89           88.10      558.1          0.10590   
237        20.48         21.46          132.50     1306.0          0.08355   
31         11.84         18.70           77.93      440.6          0.11090   
11         15.78         17.89          103.60      781.0          0.09710   
417        15.50         21.08          102.90      803.1          0.11200   
..           ...           ...             ...        ...              ...   
274        17.93         24.48          115.20      998.9          0.08855   
239        17.46         39.28          113.40      920.6          0.09812   
300        19.53         18.90          129.50     1217.0          0.11500   
53         18.22         18.70          120.30     1033.0          0.11480   
491        17.85         13.23          114.60      992.1          0.07838   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
396           0.11470         0.08580              0.05381         0.1806   
237           0.08348         0.09042              0.06022         0.1467   
31            0.15160         0.12180              0.05182         0.2301   
11            0.12920         0.09954              0.06606         0.1842   
417           0.15710         0.15220              0.08481         0.2085   
..                ...             ...                  ...            ...   
274           0.07027         0.05699              0.04744         0.1538   
239           0.12980         0.14170              0.08811         0.1809   
300           0.16420         0.21970              0.10620         0.1792   
53            0.14850         0.17720              0.10600         0.2092   
491           0.06217         0.04445              0.04178         0.1220   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
396                 0.06079  ...         14.80          27.20   
237                 0.05177  ...         24.22          26.17   
31                  0.07799  ...         16.82          28.12   
11                  0.06082  ...         20.42          27.28   
417                 0.06864  ...         23.17          27.65   
..                      ...  ...           ...            ...   
274                 0.05510  ...         20.92          34.69   
239                 0.05966  ...         22.51          44.87   
300                 0.06552  ...         25.93          26.24   
53                  0.06310  ...         20.60          24.13   
491                 0.05243  ...         19.82          18.42   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
396            97.33       675.2           0.14280            0.25700   
237           161.70      1750.0           0.12280            0.23110   
31            119.40       888.7           0.16370            0.57750   
11            136.50      1299.0           0.13960            0.56090   
417           157.10      1748.0           0.15170            0.40020   
..               ...         ...               ...                ...   
274           135.10      1320.0           0.13150            0.18060   
239           141.20      1408.0           0.13650            0.37350   
300           171.10      2053.0           0.14950            0.41160   
53            135.10      1321.0           0.12800            0.22970   
491           127.10      1210.0           0.09862            0.09976   

     concavity_worst  concave points_worst  symmetry_worst  \
396           0.3438               0.14530          0.2666   
237           0.3158               0.14450          0.2238   
31            0.6956               0.15460          0.4761   
11            0.3965               0.18100          0.3792   
417           0.4211               0.21340          0.3003   
..               ...                   ...             ...   
274           0.2080               0.11360         

In [17]:
y_train

396    B
237    M
31     M
11     M
417    M
      ..
274    M
239    M
300    M
53     M
491    B
Name: diagnosis, Length: 455, dtype: object

In [18]:
std=StandardScaler()

In [19]:
x_train,x_test=std.fit_transform(x_train),std.fit_transform(x_test)

In [20]:
label=LabelEncoder()

In [21]:
y_train,y_test=label.fit_transform(y_train),label.fit_transform(y_test)

In [22]:
y_train

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [25]:
import torch as t

In [26]:
x_train_t,x_test_t,y_train_t,y_test_t=t.from_numpy(x_train),t.from_numpy(x_test),t.from_numpy(y_train),t.from_numpy(y_test)

In [27]:
x_train_t

tensor([[-0.1842, -0.0929, -0.1692,  ...,  0.4568, -0.3603, -0.3960],
        [ 1.7630,  0.5023,  1.6248,  ...,  0.4446, -1.0437, -0.7012],
        [-0.6508, -0.1369, -0.5802,  ...,  0.5987,  2.9848,  3.0622],
        ...,
        [ 1.4976, -0.0905,  1.5035,  ...,  1.2606,  0.1219,  0.8286],
        [ 1.1316, -0.1369,  1.1318,  ...,  0.2616,  0.2065, -0.2317],
        [ 1.0282, -1.4037,  0.9015,  ..., -0.4870, -1.7702, -1.3870]],
       dtype=torch.float64)

In [28]:
import torch.nn as nn

In [34]:
class Simple_nn(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.container=nn.Sequential(nn.Linear(features,1),nn.Sigmoid())
  def forward(self,x):
    z=self.container(x)
    return z


In [37]:
x_train_t,x_test_t,y_train_t,y_test_t=x_train_t.float(),x_test_t.float(),y_train_t.float(),y_test_t.float()

In [38]:
model=Simple_nn(x_train_t.shape[1])

In [39]:
model(x_train_t)

tensor([[0.4059],
        [0.4298],
        [0.3831],
        [0.3234],
        [0.6146],
        [0.4668],
        [0.4728],
        [0.6024],
        [0.4521],
        [0.3815],
        [0.4183],
        [0.4299],
        [0.4405],
        [0.5216],
        [0.5926],
        [0.4270],
        [0.4756],
        [0.3602],
        [0.4814],
        [0.4159],
        [0.5729],
        [0.5556],
        [0.3933],
        [0.5174],
        [0.4838],
        [0.4900],
        [0.4032],
        [0.6228],
        [0.5602],
        [0.7548],
        [0.3179],
        [0.9227],
        [0.2933],
        [0.3656],
        [0.3392],
        [0.3438],
        [0.3167],
        [0.4047],
        [0.5493],
        [0.3886],
        [0.5785],
        [0.5108],
        [0.6186],
        [0.5361],
        [0.4182],
        [0.4646],
        [0.2921],
        [0.3434],
        [0.3749],
        [0.6176],
        [0.3532],
        [0.4506],
        [0.5285],
        [0.2744],
        [0.3295],
        [0

In [40]:
loss1=nn.BCELoss()

In [42]:
#ptimmizer
optimizer=t.optim.SGD(model.parameters(),lr=0.01)

In [43]:
epochs=25

In [61]:
batch_size=32


In [62]:
for i in range(epochs):
  for start_index in range(0,len(x_train_t),batch_size):
    end_index=start_index+batch_size
    x_batch=x_train_t[start_index:end_index]
    y_batch=y_train_t[start_index:end_index]
    #forward_pass
    y_pred=model(x_train_t)
    #loss
    loss_=loss1(y_pred,y_train_t.reshape(-1,1))
    #clear gradient
    optimizer.zero_grad()
    #backward()
    loss_.backward()
    #update weights
    optimizer.step()
    print(loss_)

tensor(0.4801, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4736, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4673, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4612, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4554, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4497, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4442, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4390, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4339, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4289, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4242, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4195, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4150, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4107, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4065, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4024, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3984, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3945, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3908, grad_fn=<Bina

In [63]:
model(x_train_t)

tensor([[0.3119],
        [0.9649],
        [0.8158],
        [0.8967],
        [0.9962],
        [0.5374],
        [0.4073],
        [0.9955],
        [0.0300],
        [0.1080],
        [0.0915],
        [0.0247],
        [0.9926],
        [0.0175],
        [0.0394],
        [0.0039],
        [0.0683],
        [0.9969],
        [0.9850],
        [0.7298],
        [0.0225],
        [0.5307],
        [0.1975],
        [0.0582],
        [0.0408],
        [0.0161],
        [0.9958],
        [0.0611],
        [0.0455],
        [0.0512],
        [0.9944],
        [0.2074],
        [0.9983],
        [0.9789],
        [0.9926],
        [0.3850],
        [0.1879],
        [0.9997],
        [0.1376],
        [0.2362],
        [0.0355],
        [0.0205],
        [0.0590],
        [0.7697],
        [0.0828],
        [0.0463],
        [0.9995],
        [0.3555],
        [0.9998],
        [0.0239],
        [0.9624],
        [0.0547],
        [0.1045],
        [0.9984],
        [0.0586],
        [0

In [64]:
#evaluation
with t.no_grad():
  y_pred=model(x_test_t)
  y_pred=(y_pred>0.5).int()

In [65]:
y_pred

tensor([[1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],

In [66]:
#accuracy
accuracy_=((y_pred==y_test_t).float()).mean()

In [67]:
accuracy_

tensor(0.5346)